### ISSUE TITLE
Update ToDo List

### ISSUE THREAD

**Issue by Miolus** [Miolus/german-jokes#5]
Dieser Issue zeigt den aktuellen Update-Stand.

- [x] GJ Pycord 2.0a kompatibel machen
- [x] neue `Utils` Version von InviteChecker einbauen
- [x] Verbesserung von `/daily`
- [x] Irgendwelche Performance Verbesserungen
- [x] ModPanel: Keine WebSockets mehr
- [x] Alles testen

**Comment by Miolus** [comment]
#6
